[package]
name = "proto-programmer"
version = "0.1.0"
authors = ["Usairim Isani <usairim.isani@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
